name: Mirroring

on: [push, delete]

jobs:
  to_gitea:
    runs-on: ubuntu-18.04
    steps:                                              
    - uses: actions/checkout@v1
    - uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url:
          git@git.codyrobibero.dev:12222/crobibero/Jellyfin.Channels.LazyMan.git
        ssh_private_key:                                
          ${{ secrets.GITEA_SSH_PRIVATE_KEY }}